"backend: tensorflow\nclass_name: Sequential\nconfig:\n  layers:\n  - class_name:\
  \ InputLayer\n    config:\n      batch_input_shape: !!python/tuple\n      - null\n\
  \      - 32\n      - 32\n      - 3\n      dtype: float32\n      name: dense_1_input\n\
  \      ragged: false\n      sparse: false\n  - class_name: Dense\n    config:\n\
  \      activation: relu\n      activity_regularizer: null\n      batch_input_shape:\
  \ !!python/tuple\n      - null\n      - 32\n      - 32\n      - 3\n      bias_constraint:\
  \ null\n      bias_initializer:\n        class_name: Zeros\n        config: {}\n\
  \      bias_regularizer: null\n      dtype: float32\n      kernel_constraint: null\n\
  \      kernel_initializer:\n        class_name: GlorotUniform\n        config:\n\
  \          seed: null\n      kernel_regularizer: null\n      name: dense_1\n   \
  \   trainable: true\n      units: 32\n      use_bias: true\n  - class_name: Dense\n\
  \    config:\n      activation: softmax\n      activity_regularizer: null\n    \
  \  bias_constraint: null\n      bias_initializer:\n        class_name: Zeros\n \
  \       config: {}\n      bias_regularizer: null\n      dtype: float32\n      kernel_constraint:\
  \ null\n      kernel_initializer:\n        class_name: GlorotUniform\n        config:\n\
  \          seed: null\n      kernel_regularizer: null\n      name: dense_2\n   \
  \   trainable: true\n      units: 10\n      use_bias: true\n  name: sequential_6\n\
  keras_version: 2.4.0\n"
